apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant-a-dev
  namespace: env-service
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: env-service-warehouse-dev
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: imageRepo
          value: docker.io/andycpx/kargodemo
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/AndyCpX/argo-argocd-gitops-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./repo/gitops/tenants/tenant-a/dev
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: git-commit
          config:
            path: ./repo
            messageFromSteps:
              - update-image
        - uses: git-push
          config:
            path: ./repo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant-a-staging
  namespace: env-service
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: env-service-warehouse
      sources:
        stages:
          - tenant-a-dev
  promotionTemplate:
    spec:
      vars:
        - name: imageRepo
          value: docker.io/andycpx/kargodemo
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/AndyCpX/argo-argocd-gitops-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./repo/gitops/tenants/tenant-a/staging
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: git-commit
          config:
            path: ./repo
            messageFromSteps:
              - update-image
        - uses: git-push
          config:
            path: ./repo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant-a-prod
  namespace: env-service
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: env-service-warehouse
      sources:
        stages:
          - tenant-a-staging
  promotionTemplate:
    spec:
      vars:
        - name: imageRepo
          value: docker.io/andycpx/kargodemo
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/AndyCpX/argo-argocd-gitops-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./repo/gitops/tenants/tenant-a/prod
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: git-commit
          config:
            path: ./repo
            messageFromSteps:
              - update-image
        - uses: git-push
          config:
            path: ./repo
