apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant-a-dev
  namespace: env-service
spec:
  subscriptions:
    warehouse: env-service
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/AndyCpX/argo-argocd-gitops-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          config:
            path: ./repo/gitops/stages/dev
            images:
              - image: docker.io/andycpx/kargodemo
        - uses: git-commit
          config:
            path: ./repo
            message: "chore(tenant-a-dev): update image to {{.Freight.Images[0].Tag}}"
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: env-service-tenant-a-dev
                namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant-a-staging
  namespace: env-service
spec:
  subscriptions:
    upstreamStages:
      - name: tenant-a-dev
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/AndyCpX/argo-argocd-gitops-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          config:
            path: ./repo/gitops/stages/staging
            images:
              - image: docker.io/andycpx/kargodemo
                useDigest: false
        - uses: git-commit
          config:
            path: ./repo
            message: "chore(tenant-a-staging): promote image to {{.Freight.Images[0].Tag}}"
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: env-service-tenant-a-staging
                namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant-a-prod
  namespace: env-service
spec:
  subscriptions:
    upstreamStages:
      - name: tenant-a-staging
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/AndyCpX/argo-argocd-gitops-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          config:
            path: ./repo/gitops/stages/prod
            images:
              - image: docker.io/andycpx/kargodemo
                useDigest: false
        - uses: git-commit
          config:
            path: ./repo
            message: "chore(tenant-a-prod): promote image to {{.Freight.Images[0].Tag}}"
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: env-service-tenant-a-prod
                namespace: argocd
