apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant-a-dev
  namespace: env-service
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: env-service
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/AndyCpX/argo-argocd-gitops-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          config:
            path: ./repo/gitops/stages/dev
            images:
              - image: docker.io/andycpx/kargodemo
                tag: ${{ imageFrom("docker.io/andycpx/kargodemo").Tag }}
        - uses: git-commit
          config:
            path: ./repo
            message: "chore(tenant-a-dev): update image to ${{ imageFrom(\"docker.io/andycpx/kargodemo\").Tag }}"
        - uses: git-push
          config:
            path: ./repo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant-a-staging
  namespace: env-service
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: env-service
      sources:
        stages:
          - tenant-a-dev
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/AndyCpX/argo-argocd-gitops-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          config:
            path: ./repo/gitops/stages/staging
            images:
              - image: docker.io/andycpx/kargodemo
                tag: ${{ imageFrom("docker.io/andycpx/kargodemo").Tag }}
        - uses: git-commit
          config:
            path: ./repo
            message: "chore(tenant-a-staging): promote image to ${{ imageFrom(\"docker.io/andycpx/kargodemo\").Tag }}"
        - uses: git-push
          config:
            path: ./repo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant-a-prod
  namespace: env-service
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: env-service
      sources:
        stages:
          - tenant-a-staging
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/AndyCpX/argo-argocd-gitops-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          config:
            path: ./repo/gitops/stages/prod
            images:
              - image: docker.io/andycpx/kargodemo
                tag: ${{ imageFrom("docker.io/andycpx/kargodemo").Tag }}
        - uses: git-commit
          config:
            path: ./repo
            message: "chore(tenant-a-prod): promote image to ${{ imageFrom(\"docker.io/andycpx/kargodemo\").Tag }}"
        - uses: git-push
          config:
            path: ./repo
