apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: env-service
  namespace: env-service
spec:
  subscriptions:
    - image:
        repoURL: docker.io/andycpx/kargodemo
        semverConstraint: "*"
        discoveryLimit: 10
