apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: env-service-pdb
  labels:
    app.kubernetes.io/name: env-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: env-service
